---
# this is YAML front matter
toc: true
layout: post
title: Javascript output jquery 
description:  Javascript output jquery 
courses: { csa: {week: 4, categories: []} }
categories: []
type: ccc
---

### Markdown Table
Google [markdown cheat sheet](https://www.markdownguide.org/extended-syntax/#tables) and it lead you to an outline for how to make a table.

| Make | Model | Year | Color | Price |
|------|-------|------|-------|-------|
|Ford|Mustang|2022|Red|$35,000|
|Toyota|Camry|2022|Silver|$25,00|
|Tesla|Model S|2022|White|$80,000|
|Cadillac|Broughan|1969|Black|$10,000|
|Ford|F-350|1997|Green|$15,000|
|Ford|Excursion|2003|Green|$25,000|
|Ford|Ranger|2012|Red|$8,000|
|Kuboto|L3301 Tractor|2015|Orange|$12,000|
|Ford|Fusion Energi|2015|Green|$15,000|
|Acura|XL|2006|Grey|$10,000|
|Ford|F150 Lightning|2023|Grey|$70,000|

### HTML Table
Google [w3schools html table](https://www.w3schools.com/html/html_tables.asp) and it will lead you to a tutorial on how to make tables.

In [ ]:
%%html

<h2>HTML Cell Output from Jupyter</h2>

<!-- Body contains the contents of the Document -->
<body>
    <table class="table">
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Color</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Ford</td>
                <td>Mustang</td>
                <td>2022</td>
                <td>Red</td>
                <td>$35,000</td>
            </tr>
            <tr>
                <td>Toyota</td>
                <td>Camry</td>
                <td>2022</td>
                <td>Silver</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Tesla</td>
                <td>Model S</td>
                <td>2022</td>
                <td>White</td>
                <td>$80,000</td>
            </tr>
            <tr>
                <td>Cadillac</td>
                <td>Broughan</td>
                <td>1969</td>
                <td>Black</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F-350</td>
                <td>1997</td>
                <td>Green</td>
                <td>$15,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Excursion</td>
                <td>2003</td>
                <td>Green</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Ranger</td>
                <td>2012</td>
                <td>Red</td>
                <td>$8,000</td>
            </tr>
            <tr>
                <td>Kuboto</td>
                <td>L3301 Tractor</td>
                <td>2015</td>
                <td>Orange</td>
                <td>$12,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Fusion Energi</td>
                <td>2015</td>
                <td>Guard</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Acura</td>
                <td>XL</td>
                <td>2006</td>
                <td>Grey</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F150 Lightning</td>
                <td>2024</td>
                <td>Guard</td>
                <td>$70,000</td>
            </tr>
        </tbody>
    </table>
</body>

## HTML Table in Markdown Cell with JavaScript jquery
JavaScript is a programming language that works with HTML data, CSS helps to style that data.  In this example, we are using JavaScript and CSS that was developed by others (3rd party).  Addithing the 3rd party code makes the table interactive.
- Look at the href and src on lines inside of the lines in `<head>` tags.  This is adding code to our page from others.
- Observe the `<script>` tags at the bottom of the page.  This is generating the interactive table, from the third party code, using the data `<table id="demo">` from the `<body>`.

<!-- Head contains information to Support the Document -->
<head>
    <!-- load jQuery and DataTables output style and scripts -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>var define = null;</script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
</head>

<!-- Body contains the contents of the Document -->
<body>
    <table id="md_demo" class="table">
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Color</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Ford</td>
                <td>Mustang</td>
                <td>2022</td>
                <td>Red</td>
                <td>$35,000</td>
            </tr>
            <tr>
                <td>Toyota</td>
                <td>Camry</td>
                <td>2022</td>
                <td>Silver</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Tesla</td>
                <td>Model S</td>
                <td>2022</td>
                <td>White</td>
                <td>$80,000</td>
            </tr>
            <tr>
                <td>Cadillac</td>
                <td>Broughan</td>
                <td>1969</td>
                <td>Black</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F-350</td>
                <td>1997</td>
                <td>Green</td>
                <td>$15,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Excursion</td>
                <td>2003</td>
                <td>Green</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Ranger</td>
                <td>2012</td>
                <td>Red</td>
                <td>$8,000</td>
            </tr>
            <tr>
                <td>Kuboto</td>
                <td>L3301 Tractor</td>
                <td>2015</td>
                <td>Orange</td>
                <td>$12,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Fusion Energi</td>
                <td>2015</td>
                <td>Guard</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Acura</td>
                <td>XL</td>
                <td>2006</td>
                <td>Grey</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F150 Lightning</td>
                <td>2024</td>
                <td>Guard</td>
                <td>$70,000</td>
            </tr>
        </tbody>
    </table>
</body>

<!-- Script is used to embed executable code -->
<script>
    $("#md_demo").DataTable();
</script>

## Hacks
This lesson teaches you about tables.  In this hack, it is important that you analze the difference in the styles of output shown.  
- Make your own tables, with data according to your interests.
- Describe a benefit of a markdown table.
- Try to Style the HTML table using w3schools.
- Describe the difference between HTML and JavaScript.
- Describe a benefit of a table that uses JavaScript.

<!DOCTYPE html>
<html>
<head>
    <title>Top Goal Scorers in Premier League</title>
</head>
<body>
    <table id="topScorersTable">
        <thead>
            <tr>
                <th>Rank</th>
                <th>Name</th>
                <th>Goals</th>
                <th>Assists</th>
                <th>Played</th>
                <th>Goals per 90</th>
                <th>Mins per Goal</th>
                <th>Total Shots</th>
                <th>Goal Conversion</th>
                <th>Shot Accuracy</th>
            </tr>
        </thead>
        <tbody>
            <!-- Table data will be added dynamically using JavaScript -->
        </tbody>
    </table>
    <script>
        // Data for the top goal scorers
        var topScorersData = [
            [1, "Erling Haaland", 6, 1, 4, 1.54, 58, 18, "33%", "56%"],
            [2, "Evan Ferguson", 4, 0, 4, 1.75, 52, 12, "33%", "75%"],
            [2, "Bryan Mbeumo", 4, 0, 4, 1.00, 90, 8, "50%", "75%"],
            [4, "Taiwo Awoniyi", 3, 1, 4, 1.08, 83, 7, "43%", "43%"],
            [4, "Jarrod Bowen", 3, 1, 4, 0.75, 120, 10, "30%", "60%"],
            [4, "Solly March", 3, 0, 4, 0.85, 106, 7, "43%", "86%"],
            [4, "Son Heung-min", 3, 0, 4, 0.83, 109, 7, "43%", "57%"],
            [4, "Odsonne Édouard", 3, 0, 4, 0.79, 113, 15, "20%", "53%"]
        ];
        // Get the table body element
        var tableBody = document.querySelector("#topScorersTable tbody");
        // Function to add a row to the table
        function addRow(data) {
            var row = document.createElement("tr");
            data.forEach(function(cellData) {
                var cell = document.createElement("td");
                cell.textContent = cellData;
                row.appendChild(cell);
            });
            tableBody.appendChild(row);
        }
        // Populate the table with data
        topScorersData.forEach(function(rowData) {
            addRow(rowData);
        });
    </script>
</body>
</html>